### ISSUE TITLE
SSSD race condition

### ISSUE THREAD

**Issue by Xenopathic** [the-linux-schools-project/karoshi-client#123]
SSSD can start before networking is up, which results in it going into offline mode and handing out offline credentials until it checks again (usually after 10 minutes). On machines with fast network cards, this isn't a problem, but some chipsets establish a link very slowly. Solution lies somewhere in the Upstart init script. No hacks if possible please!

**Comment by Xenopathic** [comment]
Should be fixed with 5f3558ba62cdf8c08e2467aa2ed63f764f631f25 (testing at DGSB - @jhosier please update this issue with your findings)

**Comment by jhosier** [comment]
No immediate problems following this fix. Have tested that I can still login on a normal network machine.
