### ISSUE TITLE
Grub timeout  set to 10 seconds

### ISSUE THREAD

**Issue by jhosier** [the-linux-schools-project/karoshi-client#124]
Since Karoshi-Client 4.3 the grub screen counts down from 10 seconds slowing down boot time.
This is a regression in the sense that Karoshi-Client 4.2 did not do this.

**Comment by ojphillips** [comment]
Would setting this to 5 seconds be to quick?

**Comment by jhosier** [comment]
Firstly, in Version 4.4 this regression bug sometimes means that the grub menu appears and does not countdown at all it just sits there waiting for you to select Ubuntu, so setting the timer to a lower number would not help, especially since the timer in /etc/default/grub is already set to 0.
Secondly, note to Owen - please do not close a ticket with a comment like "Fixed slow boot times" without saying in what way you have fixed it. That is not helpful and is just irritating.
Please state how you feel it should be fixed and then we will review your comment.

**Comment by ojphillips** [comment]
Hmm, i will look into this i found some grub settings in isolinux.cfg, i will see what i can do.

**Comment by ojphillips** [comment]
would you mind testing something?

add: GRUB_RECORDFAIL_TIMEOUT=0
to /etc/default/grub

and then sudo upgrade-grub

**Comment by jhosier** [comment]
FIXED ... OK, after putting GRUB_RECORDFAIL_TIMEOUT=0 into /etc/default/grub and then running sudo upgrade-grub the menu will not now appear at all.
By this I mean that if the PC experiences power loss or is interrupted by a reboot when booting up, at the next boot it continues without the grub2 menu appearing. This is good.
However, if you then want to try to bring up the boot by holding down Left Shift when booting, or by pressing Left Shift key quickly when booting it now does not come up for that either.
This to me is not an issue since the only thing you can do at the grub menu is boot Ubuntu or the recovery mode and recovery mode is not used since you need the root password which I don't know, and it is much easier to just re-install a client than to try to fix it anyway.
This can be put forward as a fix for this bug.

**Comment by ojphillips** [comment]
When i get the remaster script working this will be added to the next client version.

**Comment by jhosier** [comment]
After investigating possible grub settings we decided that the following changes need to be made to /etc/default/grub:
GRUB_TIMEOUT=5 - This will display the menu at each boot up for about 3 seconds. This is required otherwise the menu will not appear even if you press shift because you need to input boot parameters like nomodeset
GRUB_RECORDFAIL_TIMEOUT=0 - This will prevent the 30 second time out after failed boot or power loss
GRUB_GFXPAYLOAD_LINUX=keep - This will keep the splash boot up screen after grub graphical 
GRUB_BACKGROUND=/opt/karoshi/linuxclientsetup/images/background.png - Makes the 3 second grub menu pretty :-)
