### ISSUE TITLE
Software installation not available

### ISSUE THREAD

**Issue by Xenopathic** [the-linux-schools-project/karoshi-client#93]
The ability to install software was removed previously, and needs to be re-implemented. Possible implementation idea: calculate hashes of the software install list, and if it has changed, do an install from the `karoshi-system-upgrade` Upstart job, performing a full system upgrade at the same time. This allows the upgrade to occur asynchronously, so boot times are not impaired. Only issue is the potential for corruption if the machine is shut down prematurely and hasn't finished installing software.

**Comment by mpsharrad** [comment]
I've modifed the web management to create file information for software installation on the clients:

All of the information is in:
netlogon/linuxclient/karoshi4/software/install/

Flag files
all_install - install software listed in all_software on all linux clients
all_updates - all clients will update on boot
$location_install  - install software listed in $location_software on all linux clients set to this location
$location_updates - clients in a $location will update on boot

Data files
all_software -  list of software to install for all clients
$location_software -  list of software to install for clients in a location

**Comment by Xenopathic** [comment]
mpsharrad: What happens if a location is created called 'all'? :laughing:

**Comment by mpsharrad** [comment]
As long as they really mean "all" then all will be ok !

**Comment by Xenopathic** [comment]
@mpsharrad: What is happening with the old flag file, `netlogon/linuxclient/$LINUX_VERSION/enable_updates` ? I take it that `all_updates` replaces that?
