### ISSUE TITLE
Fix Firefox + Thunderbird dictionaries

### ISSUE THREAD

**Issue by Xenopathic** [the-linux-schools-project/karoshi-client#95]
This is an issue to track the implementation of @Eldara98 's work on l10n with Firefox and Thunderbird.

Since the introduction of l10n, Firefox and Thunderbird default to the French dictionary, used for spell checking. They seem to completely ignore the system locale settings, and there seems to be no way of forcing a locale in prefs.js.

**Comment by Eldara98** [comment]
This is not a problem in Thunderbird, as the code I implemented to fix this problem before worked in that case. Oddly, it is only a Firefox issue.
