### ISSUE TITLE
Save Firefox preferences on logout

### ISSUE THREAD

**Issue by Xenopathic** [the-linux-schools-project/karoshi-client#97]
Currently, places.sqlite is being saved on logout for bookmarks and history, but preferences are not. It would be useful to have these saved as well. The key file here is prefs.js (*not* user.js!), but there may be some .sqlite files that need to be saved as well.

cc @Eldara98

**Comment by Xenopathic** [comment]
Another side effect of this: we currently supress notifications, so a user can get working ASAP. This is bad UX, since new features should be notified to the user at least once. Saving `prefs.js` will store the notification status, so the user gets prompted once and never again. In addition, we should remove the current notification supression code from `prefs.js` in the skel (if we need to keep any of `prefs.js` at all).

**Comment by Eldara98** [comment]
It really depends on what preferences you want. By default, any settings in ```user.js``` override those in ```prefs.js```, so perhaps it would be better to move the system of preferences to ```user.js``` and then keep that instead?
Also, ```prefs.js``` would only save user preferences, i.e. those that are changeable in the ```about:config``` dialogue. To save other types of preferences, such as saved passwords, site-specific preferences, autocomplete history etc, more files will require saving on logout.

**Comment by Xenopathic** [comment]
Fixed in #108
